# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Comment',
        ),
    ]
