# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180822_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='comment_text',
            new_name='choice_text',
        ),
    ]
