# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180822_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='body',
        ),
    ]
