# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180822_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Choice',
        ),
    ]
