# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180824_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='body',
            new_name='choice_text',
        ),
    ]
